name: Terraform

on:
  push:
    branches: [master]
    paths: ['terraform/**', '.github/workflows/terraform.yml']
  pull_request:
    branches: [master]
    paths: ['terraform/**', '.github/workflows/terraform.yml']
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  terraform:
    uses: Xomware/github-actions/.github/workflows/terraform.yml@v1
    with:
      app: today-in-sports
